name: PitchBlack [PBRP] for Spacewar

on:
  workflow_dispatch:
    inputs:
      MANIFEST:
        description: 'PBRP Manifest'
        required: true
        default: 'https://github.com/PitchBlackRecoveryProject/manifest_pb.git'
      MANIFEST_BRANCH:
        description: 'PBRP Manifest Branch'
        required: true
        default: 'android-12.1'
        type: choice
        options:
        - android-12.1
      DEVICE_TREE:
        description: 'Custom Recovery Tree' # Your already made Device Tree for TWRP
        required: true
        default: 'https://github.com/nitheshd30/OFRP-device_nothing_Spacewar.git' 
      DEVICE_TREE_BRANCH:
        description: 'Custom Recovery Tree Branch' # Your Device Tree Branch, make sure it's right.
        required: true
        default: 'master'
      DEVICE_PATH:
        description: 'Specify your Device Path' # As is, just like your DEVICE_PATH in your BoardConfig.mk
        required: true
        default: 'device/nothing/Spacewar'
      DEVICE_NAME:
        description: 'Specify your Device Codename' # As is, just like your PRODUCT_DEVICE in your device tree.
        required: true
        default: 'Spacewar'
      BUILD_TARGET:
        description: 'Specify your Build Target' # Pick among boot, recovery and vendor_boot
        required: true
        default: 'boot'
        type: choice
        options:
        - boot
      LDCHECK:
        description: 'Use LDCHECK'
        required: false
        default: 'false'
        type: boolean
      LDCHECKPATH:
        description: 'Path of blobs to check' # Use it know what kind of dependencies your missing for decryption blobs.
        required: true
        default: ''
        type: choice
        options:
        - system/bin/qseecomd
        - system/bin/android.hardware.gatekeeper@1.0-service-qti
        - system/bin/android.hardware.keymaster@4.0-service-qti
        - system/bin/android.hardware.keymaster@4.1-service-qti
